if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("CometInstantGamesPlayerRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5228833640461394"}),null);
__d("CometInstantGamesPlayerRootQuery$Parameters",["CometInstantGamesPlayerRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometInstantGamesPlayerRootQuery_facebookRelayOperation"),metadata:{},name:"CometInstantGamesPlayerRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometInstantGamesPlayerRHCQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4958141330939335"}),null);
__d("CometInstantGamesPlayerRHCQuery$Parameters",["CometInstantGamesPlayerRHCQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometInstantGamesPlayerRHCQuery_facebookRelayOperation"),metadata:{},name:"CometInstantGamesPlayerRHCQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("InstantApplicationContextTokenInputCreator.entrypointutils",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){var d=null;switch(c){case"THREAD":d={thread_id:b};break;case"STORY":d={story_token:b};break;case"GROUP":d={group_id:b};break;case"LINK":d={link_fragment:b};break;default:d=Object.freeze({});break}return{app_id:a,context_source_id:b,key:d}}f.getTokenInput=a}),66);
__d("InstantGamesTrackingData",[],(function(a,b,c,d,e,f){"use strict";a=function(){function a(a,b,c){this.$1=a,this.$2=b,this.$3=c}var b=a.prototype;b.getEcosystem=function(){return this.$1};b.getSurface=function(){return this.$2};b.getFeature=function(){return this.$3};b.serialize=function(){return this.$1+"~"+this.$2+"~"+this.$3};return a}();f["default"]=a}),66);
__d("CometGamingImpressionLogger.react",["react","useGamingVideoDestinationEventLogger","useSinglePartialViewImpression"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=d("react").useCallback;function a(a){var b=a.children,d=a.dataToLog;a=c("useGamingVideoDestinationEventLogger")();var e=a.logImpression;a=i(function(a){if(a==null)return;e(d)},[d,e]);a=c("useSinglePartialViewImpression")({onImpressionStart:a});return h.cloneElement(b,{ref:a})}g["default"]=a}),98);
__d("InstantGameEnvironmentType.facebook",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum").Mirrored(["CANVAS","COPLAY","STANDARD","VIDEO_PLUGIN"]);c=a;f["default"]=c}),66);
__d("InstantGameEnvironmentType",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({STANDARD:"standard",COPLAY:"coplay",CANVAS:"canvas",VIDEO_PLUGIN:"video_plugin"});c=a;f["default"]=c}),66);
__d("InstantGameEnvironmentTypeUtils.facebook",["$InternalEnumUtils","InstantGameEnvironmentType"],(function(a,b,c,d,e,f,g){a=d("$InternalEnumUtils").createToJSEnum(c("InstantGameEnvironmentType"));b=d("$InternalEnumUtils").createFromJSEnum(c("InstantGameEnvironmentType"));g.toJSEnum=a;g.fromJSEnum=b}),98);
__d("CometInstantGamesPlayerRoot.entrypoint",["CometInstantGamesPlayerRHCQuery$Parameters","CometInstantGamesPlayerRootQuery$Parameters","InstantApplicationContextTokenInputCreator.entrypointutils","InstantGameEnvironmentTypeUtils.facebook","JSResourceForInteraction","WebPixelRatio","gkx"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var e;e=(e=d("InstantGameEnvironmentTypeUtils.facebook").fromJSEnum(a.routeProps.environmentType))!=null?e:"STANDARD";var f=!c("gkx")("5493")||e==="CANVAS",g=f&&e!=="CANVAS"&&c("gkx")("4478");return{extraProps:babelHelpers["extends"]({},a.routeParams,{hasRHC:f}),queries:{instantGamesPlayerRHCQuery:{options:{},parameters:b("CometInstantGamesPlayerRHCQuery$Parameters"),variables:{app_id:a.routeProps.appID,has_community:g,has_rhc:f,scale:d("WebPixelRatio").get()}},instantGamesPlayerRootQuery:{options:{},parameters:b("CometInstantGamesPlayerRootQuery$Parameters"),variables:{app_id:a.routeProps.appID,cloud_binary_id:a.routeParams.cloud_binary_id,cloud_host_override_cluster:a.routeParams.cloud_host_override_cluster,cloud_host_override_host:a.routeParams.cloud_host_override_host,cloud_host_override_pop:a.routeParams.cloud_host_override_pop,cloud_host_override_port:a.routeParams.cloud_host_override_port,cloud_host_override_site_key:a.routeParams.cloud_host_override_site_key,context_source_id:a.routeParams.context_source_id,entry_point_video_id:a.routeParams.entrypoint_video_id,environment_type:e,game_id:a.routeProps.appID,is_comet_on_mobile:a.routeProps.isCometOnMobile,ota_update:a.routeParams.ota_update,session_id:(g=a.routeParams.session_id)!=null?g:(f=a.timeSpentMetaData)==null?void 0:(e=f.session_ids)==null?void 0:e.cg_session_id,source:a.routeProps.source,token_input:d("InstantApplicationContextTokenInputCreator.entrypointutils").getTokenInput(a.routeProps.appID,a.routeParams.context_source_id,(g=a.routeParams.context_type)!=null?g:"GENERIC"),useExperimentalInstantGamesContextualPlayerPresentation:c("gkx")("1301")}}}}},root:c("JSResourceForInteraction")("CometInstantGamesPlayerRoot.react").__setRef("CometInstantGamesPlayerRoot.entrypoint")};g["default"]=a}),98);
__d("InstantGamesWebHubEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1743697");c=b("FalcoLoggerInternal").create("instant_games_web_hub_events",a);e.exports=c}),null);
__d("useInstantGamesWebHubImpressionLogging",["InstantGamesWebHubEventsFalcoEvent","useSinglePartialViewImpression"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b=c("useSinglePartialViewImpression")({onImpressionStart:function(){var b=babelHelpers["extends"]({},a,{event:"impression"});c("InstantGamesWebHubEventsFalcoEvent").log(function(){return b})}}),d=function(b){var d=babelHelpers["extends"]({},a,b,{event:"click"});c("InstantGamesWebHubEventsFalcoEvent").log(function(){return d})};return{impressionRef:b,logClick:d}}g["default"]=a}),98);
__d("XCometInstantGamesCategoryControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/games/instantgames/category/",Object.freeze({category:400,sort_type:"recommended"}),void 0);b=a;g["default"]=b}),98);
__d("XCometInstantGamesHubControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/gaming/play/",Object.freeze({sort_type:"recommended",category:400}),void 0);b=a;g["default"]=b}),98);
__d("XCometInstantGamesHubPlayControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/gaming/play/{game_or_link}/{?link_fragment}/",Object.freeze({source:"www_unknown",skip_check:!1,prefer_close:!1,ota_update:!1}),void 0);b=a;g["default"]=b}),98);